### ISSUE TITLE
lib/rss/parser.rb:163:parse being compiled causes a failure

### ISSUE THREAD

**Issue by mgaudet** [rubyomr-preview/ruby#9]
```
magaudet@ubuntu1604VM:~/open/ruby_24 (ruby_2_4_omr_preliminary_contribution)*$ OMR_JIT_OPTIONS='-Xjit:count=0,limit={*parser.rb:163:parse*}' LD_LIBRARY_PATH=$PWD ./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems "./test/runner.rb" --ruby="./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems" --excludes-dir=./test/excludes test/rss
Run options: "--ruby=./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems" --excludes-dir=./test/excludes

# Running tests:

[ 22/305] RSS::TestAtomCore#test_to_xml = 0.01 s                       
  1) Error:
RSS::TestAtomCore#test_to_xml:
LocalJumpError: no block given
    /home/magaudet/open/ruby_24/lib/rss/parser.rb:80:in `parse'
    /home/magaudet/open/ruby_24/test/rss/test_atom.rb:220:in `test_to_xml'

<further failures snipped> 
/home/magaudet/open/ruby_24/test/lib/minitest/unit.rb:934: [BUG] vm_call_cfunc - cfp consistency error
ruby 2.4.0dev (2016-11-17 ruby_2_4_omr_p.. 56821) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0019 p:---- s:0108 e:000107 CFUNC  - :map
c:0018 p:0129 s:0104 e:000103 METHOD - /home/magaudet/open/ruby_24/test/lib/minitest/unit.rb:934
c:0017 p:0054 s:0092 e:000091 METHOD - /home/magaudet/open/ruby_24/test/lib/test/unit.rb:914
c:0016 p:0016 s:0085 e:000083 BLOCK  - /home/magaudet/open/ruby_24/test/lib/test/unit.rb:494 [FINISH]
c:0015 p:---- s:0079 e:000078 CFUNC  - :each
c:0014 p:0073 s:0075 e:000074 METHOD - /home/magaudet/open/ruby_24/test/lib/test/unit.rb:492
c:0013 p:0014 s:0068 e:000067 METHOD - /home/magaudet/open/ruby_24/test/lib/test/unit.rb:530
c:0012 p:0144 s:0061 e:000060 METHOD - /home/magaudet/open/ruby_24/test/lib/minitest/unit.rb:885
c:0011 p:0010 s:0050 e:000049 METHOD - /home/magaudet/open/ruby_24/test/lib/minitest/unit.rb:1096
c:0010 p:0010 s:0046 e:000045 BLOCK  - /home/magaudet/open/ruby_24/test/lib/minitest/unit.rb:1083 [FINISH]
c:0009 p:---- s:0042 e:000041 CFUNC  - :each
c:0008 p:0057 s:0038 e:000037 METHOD - /home/magaudet/open/ruby_24/test/lib/minitest/unit.rb:1082
c:0007 p:0020 s:0033 e:000032 METHOD - /home/magaudet/open/ruby_24/test/lib/minitest/unit.rb:1070
c:0006 p:0012 s:0028 e:000027 METHOD - /home/magaudet/open/ruby_24/test/lib/test/unit.rb:682
c:0005 p:0022 s:0022 e:000021 METHOD - /home/magaudet/open/ruby_24/test/lib/test/unit.rb:33
c:0004 p:0045 s:0017 e:000016 METHOD - /home/magaudet/open/ruby_24/test/lib/test/unit.rb:991
c:0003 p:0015 s:0013 e:000012 METHOD - /home/magaudet/open/ruby_24/test/lib/test/unit.rb:995
c:0002 p:0304 s:0008 E:001d38 EVAL   - ./test/runner.rb:40 [FINISH]
c:0001 p:0000 s:0003 E:000d40 (none) - [FINISH]
```

**Comment by mgaudet** [comment]
Appears to be related to #16. I have a temporary fix I'll be pushing up (probably tomorrow :sleepy: )

**Comment by mgaudet** [comment]
Closed by https://github.com/rubyomr-preview/ruby/pull/17/commits/02dcfdfdbca72bc300d804a66dd586de2b86178b , part of Pull #17
